### ISSUE TITLE
Could it be possible to provide a zipped version for the fileonly?

### ISSUE THREAD

**Issue by Sami32** [pinterf/AviSynthPlus#17]
Hello

Could it be possible to provide a zipped version for the fileonly? **AvisynthPlus-r2728-MT-filesonly.zip**

The reason of a such request is that it make it available for developpers to directly script the extraction from Maven, Gradle or Ant...
7Z is not widely supported as Zip or Tar.gz so the direct extraction is often not possible, also if some specific plugin sometimes exist, so it ask us host such compressed files on sites like Sourceforge or Bintray, for example, and uncompressed them.

Cheers

**Comment by pinterf** [comment]
No problem, next release will contain a zipped version as well besides the 7z
