### ISSUE TITLE
Switch between x86 and x86_version

### ISSUE THREAD

**Issue by Ilya87** [pinterf/AviSynthPlus#24]
AnimeIVTC uses some old plugins that exist only in x86 versions and when I try to load them using LoadPlugin get message "Cannot load a 32 bit DLL in 64 bit Avisynth". My OS is Windows 10 x64, so is there any way to make Avisynyh+ r2772 start in x86 mode?

**Comment by pinterf** [comment]
Installer deployes both x86 and x64 version, so you can start the 32bit version of Avisynth+. But it depends on the host application which Avisynth version will be used. If you use 32 bit AvspMod or VirtualDub2 or x264, it will use 32 bit (x86) Avisynth installation. When you use StaxRip, it exists only in 64 bit flavour so you won't use your old plugins. But you can always ask for an x64 versions on doom9 forums, many old filters were recompiled lately to have a proper x64 version. Ypi can check this page as well if there is an x64 version for you: http://avisynth.nl/index.php/AviSynth%2B#AviSynth.2B_x64_plugins. Or simply ask on https://forum.doom9.org/showthread.php?t=168856

**Comment by Ilya87** [comment]
Thank you!
