### ISSUE TITLE
Can you include sysinfo in avisynth dll?

### ISSUE THREAD

**Issue by Onemeshnik** [pinterf/AviSynthPlus#33]
Multithreads based on threads, it's logical to link them with numbers of cores. IMO at least info about numbers of logical/physical CPUs should be included.

There is sysinfo plugin, 
https://forum.doom9.org/showthread.php?t=176131
but it's much faster end easier to set threads number nanually that load plugin. Using internal variables is much easier

**Comment by pinterf** [comment]
I know that plugin, it is maintained properly, it has now better place as a separate plugin.
