### ISSUE TITLE
Allow to use {} instead eval(""" """)

### ISSUE THREAD

**Issue by Onemeshnik** [pinterf/AviSynthPlus#34]
You extended script language for using 
If (x>0) {

}
Instead of 
x>0? eval("""

""")

But if you want to use easier format, you need to rewrite your script.

If you allow {} instead eval(""" """) you just can find and replace eval(""" to { and """) to }
So you get syntax highlight and you do not need rewrite script

**Comment by pinterf** [comment]
Sorry, I don't think that existing Avisynth syntax should be modified just to have an easier text editor task for the person who updates old scripts. On the other hand, one can only do that if the string is a single whole constant, and is not a result of concatenation.

**Comment by Onemeshnik** [comment]
Eval construction is evil (when I started it, I did not know avisynth). Official instruction do not contain instruction about avisynth+ extensions so, most of scripts do not use that.  http://avisynth.nl/index.php/Block_statements

![image](https://user-images.githubusercontent.com/49478061/58592181-8cb30000-8270-11e9-9e6b-6d7be878b11e.png)
![image](https://user-images.githubusercontent.com/49478061/58592121-773dd600-8270-11e9-8be3-20d13695d06e.png)

So for using comfortable format you have to port statement to another format which is more unfortable. 
Avisynth+ already has GScript for more comfortable syntax, but for old script it's useless :( Thanks anyway

**Comment by pinterf** [comment]
Yep, there can be plans. But this is a freetime project. Resources are extremely limited, both for coding (lately only me) and for creating up-to-date documentation (additional few people).

**Comment by realfinder** [comment]
there are script use them https://github.com/AviSynth/avs-scripts/blob/master/maa2+.avsi and there are others https://github.com/AviSynth/avs-scripts but most them outdated now

most scripts don't use that avs+ feature to keep normal avs compatibility but there are some exclusive avs+ script and maybe they will become more and more by they time
