### ISSUE TITLE
Master branch is dead

### ISSUE THREAD

**Issue by Onemeshnik** [pinterf/AviSynthPlus#35]
If you go to https://github.com/pinterf/AviSynthPlus you see fistly was changed 6 years ago. I was confused when finded active branch. Imho its more logical to move mt branch to master

All navigation like releases->code returns old branch

**Comment by pinterf** [comment]
All I'm planning to make MT the default branch

**Comment by vadosnaprimer** [comment]
This is really easy in github interface.

Settings -> Branches -> Default branch -> Set to `MT` -> Update.

**Comment by pinterf** [comment]
Thanks :) I know it well, done with mvtools lately, but things go slowly. I didn't want to do it until I read more about the side effects (are forks affected? etc... I'm not a git power user who knows everything by heart)

**Comment by vadosnaprimer** [comment]
Forking and cloning inherits the branch that was configured as default by the time of cloning/forkng (just tested).

**Comment by Onemeshnik** [comment]
I am not github user and I spent quite lot time for me just for finding real active branch. As I get, If you do any bad thing, you can revert changes

**Comment by pinterf** [comment]
Default branch changed to MT
