### ISSUE TITLE
Subtitle halo size

### ISSUE THREAD

**Issue by vadosnaprimer** [pinterf/AviSynthPlus#36]
I've been staring at the code for months and completely failed to figure out how to change the hardcoded subtitle halo width without breaking 100% of the subtitle functionality. I don't know why it was made so unbearably cryptic, fixed, and unexpandable.

Do you know if it's even possible at this point to make it more configurable? On standard DVD footage resolution it might look fine, but once you go HD or higher, increasing subtitle font size accordingly, halo gets vanishingly smaller compared to font size.

**Comment by pinterf** [comment]
Had a short look at, yes, it's quite cryptic. Seems that it'd be easier to rewrite a general one (once understood what should happen) than patching those hardcoded dimensions and make the code more unreadable.

**Comment by vadosnaprimer** [comment]
Yup. And even rewriting wouldn't make it better than what assrender plugin can do. Sounds like a dead end.
