### ISSUE TITLE
Error trying to display the clip

### ISSUE THREAD

**Issue by TbtBI** [pinterf/AviSynthPlus#37]
Hi. r2885 is returning "Error trying to display the clip" when trying to display high bit depth video with [AvsPmod](https://github.com/gispos/AvsPmod).
```
ffvideosource(8-bit.video)
convertbits(10...16)
```
No issue with r2882 (83b1e85).

**Comment by pinterf** [comment]
Then it must be because of this commit:
https://github.com/pinterf/AviSynthPlus/commit/4ca51d3f45af69cc4a935b0fac5466811544be9b
AvsPmod is probably using some of the mentioned converter functions on non-8-bit source.

**Comment by TbtBI** [comment]
Thanks. I guess it's better to report that issue on @gispos repo instead of your AvsPmod repo?

**Comment by pinterf** [comment]
No, it was on my side. Fixed.

**Comment by TbtBI** [comment]
Thanks for the fix.

**Comment by pinterf** [comment]
Thanks for the report.
