### ISSUE TITLE
AviSynth crashes if use ConverttoYV24 with UnSharpMask filter

### ISSUE THREAD

**Issue by Bassquake** [pinterf/AviSynthPlus#39]
As title really. Crashes using built in UnSharpMask with ConverttoYV24.

Simply put this in an avs file:

`AVIFileSource("test.avi", audio=true).converttoYV24().UnsharpMask(strength=60, radius=3, threshold=8)`

And render it in ffmpeg or open in AvsPMod. It will crash out in AvsPMod and ffmpeg just doesn't output anything, just returns to command.

Tested with **DirectShowSource** which also crashes.

Crashes with **ConverttoYUV444** as well.

It doesn't mention any limitations in the [wiki for UnSharpMask](http://avisynth.nl/index.php/WarpSharp/UnsharpMask).

Works fine with **ConverttoYV12** though.

Edit:
Program Versions
Avisynth+ v2772 (20181220)
FFMpeg 4.2

**Comment by pinterf** [comment]
UnsharpMask is not an internal filter, could you provide a download link for the version you are using? You may also check for a newer one if it's not the latest one?

**Comment by Bassquake** [comment]
Hm. Seems to be from Warpsharp.dll. Version I have is 20080325. 

http://avisynth.nl/index.php/WarpSharp

Doesn't seem to be newer version. Recommend any alternatives?

**Comment by pinterf** [comment]
As I read the wiki, the plugin is from 2008, supports even the old Avisynth 2.58, and handles YV12 and YUY2 colorspaces. So you cannot use YV24 with them.
Other than those two (not counting RGB) color spaces probably did not even exist at that time, so the plugin cannot tell that the YV24 format is not allowed.
I do not know more about it than we discussed in https://forum.doom9.org/showthread.php?p=1876526#post1876526

**Comment by Bassquake** [comment]
Found the updated version (2011-06-15) mentioned on that forum, same issue.

Using MSharpen instead now as it accepts YV24 and YUV444.

http://avisynth.nl/index.php/MSharpen

Thanks for responding.
