### ISSUE TITLE
Crash when ternary operator is used with HBD

### ISSUE THREAD

**Issue by TbtBI** [pinterf/AviSynthPlus#40]
Hi, using [this script](https://pastebin.com/raw/r9E1FGWJ) with 8-bit video everything is fine. When the video is  > 8-bit there is crash without any error message. 
Replacing `NumComponents(input) > 1 ? input == ExtractY(input) : NOP()` with `if (NumComponents(input) > 1)
    {
        input = ExtractY(input)
    }` works fine with every bit depth.
Used avs+ r2915 / 3.4.

**Comment by pinterf** [comment]
Try input = ExtractY(input) instead of input == ExtractY(input)

**Comment by TbtBI** [comment]
`input = ExtractY(input)` - returns "Script error: expected ':' " in AvsPmod.

**Comment by pinterf** [comment]
I'm from mobile, just a quick help.
Don't mix assignment = with comparison ==.
Don't put assignment operator on ternary operator's true/false branch.
Find and check proper language syntax on avisynth.nl or ask it on forums

**Comment by TbtBI** [comment]
But you suggested: "Try input = ExtractY(input) instead of input == ExtractY(input)".

**Comment by pinterf** [comment]
I was wrong.
`input = NumComponents(input) > 1 ? ExtractY(input) : input`

**Comment by TbtBI** [comment]
That works. Thanks.

But shouldn't `NumComponents(input) > 1 ? input == ExtractY(input) : NOP()` have the same behavior for both 8-bit video and >8-bit video?
