### ISSUE TITLE
ffmpeg / VirtualDub Crash after some SSRC manipulations and concatenation

### ISSUE THREAD

**Issue by belonesox** [pinterf/AviSynthPlus#46]
ffmpeg (all versions, from 2016 to 2019) and VirtualDub crashed (randomly, but with probablility > 50%) after some manipulations
(SSRC and clip concatenation).

Minimal sample to reproduce:
https://drive.google.com/open?id=1g8HKn2CVYAbQ1pRsNNiVmxcELLIA_OX9

AVS++ on 4c4635eaa32689336d45a26c5b326598242d6b2b

Old AVSynth works OK with this.

**Comment by pinterf** [comment]
Access viola 0xC0000005, shibatch.dll is the culprit. Fixed for my tests, will update my git soon.

**Comment by pinterf** [comment]
Fixed by 41f591370d0affad0a7264c94d23caa0db82e2c9
