### ISSUE TITLE
both masktools2 and expr have different clamp_float type

### ISSUE THREAD

**Issue by TbtBI** [pinterf/AviSynthPlus#48]
Hi,

I have "the named argument "clamp_float" to Expr had the wrong type" error when something like that is used:
`mt_lut("...", use_expr=3)`
Used masktools2 2.2.20@64efe33, avs+ 3.5.0@a34ede9.

**Comment by pinterf** [comment]
Update your masktools source, it has been changed since that commit

**Comment by TbtBI** [comment]
Thanks.
