### ISSUE TITLE
Error trying to display the clip

### ISSUE THREAD

**Issue by TbtBI** [pinterf/AviSynthPlus#49]
Hi,

I have that error when trying to load YUV video with AvsPmod with avs+ compiled from [27fceb4](https://github.com/pinterf/AviSynthPlus/commit/27fceb43e18489104253e6b46476fb2e880128f8). I tried ConvertToRGB() and got "ConvertYUV444ToRGB: Only 4:4:4 data input accepted".
avs+ compiled from [4a86862](https://github.com/pinterf/AviSynthPlus/commit/4a868628f3ed32fc0ba2816d9dd05010c7d45490) is ok.

**Comment by pinterf** [comment]
Thanks, fixed, side effect of a mega-cleanup :(

**Comment by TbtBI** [comment]
Thanks.
